apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjNE56azBOek14Tml3aWFXRjBJam94TnpnM09UUTNNekUyZlEuc1Z4aDdVa0lyMjd4Yk5xRmI5LXJMU08yQWVlUG9xSUtlYnh3Z0lUYk8zUQ==
